import programIndex from "../data/programs-index.json";
import {
  DEFAULT_TERM_SPAN,
  type Faculty,
  type ProgramIdentity,
  programTermSpan,
  shortName,
} from "./programs";

// Client-safe index over programs — name, term span, and specialization
// slug+name for every program, WITHOUT the ~2 MB of rule trees. Heavy
// detail is fetched per-program on demand (see lib/programDetail). Generated by
// scripts/build-program-index.ts from data/programs.json.
export interface ProgramMeta {
  name: string;
  numberOfTerms?: number;
  specializations?: { slug: string; name: string }[];
}

// Null prototype: program ids arrive from stored plans and URLs, so lookups for
// keys like "constructor" must miss instead of returning Object.prototype
// members (truthy, then `meta.name` is undefined and identity building crashes).
const INDEX: Record<string, ProgramMeta> = Object.assign(
  Object.create(null),
  programIndex as Record<string, ProgramMeta>,
);

export function programMeta(id: string | null | undefined): ProgramMeta | null {
  return (id && INDEX[id]) || null;
}

/** `id → name`, or undefined for an unknown id. */
export function programMetaName(id: string): string | undefined {
  return INDEX[id]?.name;
}

/** Every `[id, meta]` pair — for building name/normalization tables. */
export function programMetaEntries(): [string, ProgramMeta][] {
  return Object.entries(INDEX);
}

/** A specialization's slug+name (index-level), or null. Heavy spec rules live in detail. */
export function getSpecializationMeta(
  programId: string,
  specializationSlug: string,
): { slug: string; name: string } | null {
  return (
    INDEX[programId]?.specializations?.find(
      (s) => s.slug === specializationSlug,
    ) ?? null
  );
}

// Aliases (lowercased) that resolve prereq program-restrictions to a plan when
// prose uses a different phrasing than the registry name ("Architecture" →
// Architectural Studies). Prose tokens only; a miss just falls back to "check".
const PROGRAM_RESTRICTION_ALIASES: Record<string, string[]> = {
  "computer science": ["cs"],
  "software engineering": ["se"],
  "systems design engineering": ["syde"],
  // UWFlow says "Architecture students only"; the registry calls these
  // "Architectural Studies" / "Architectural Engineering".
  "architectural studies": ["architecture"],
  "architectural engineering": ["architecture"],
  "accounting and financial management": ["afm"],
  "computing and financial management": ["cfm"],
  "mathematical finance": ["math fin", "math finance"],
  "business administration and mathematics double degree": [
    "bba/bmath",
    "bba and bmath",
    "busmath",
  ],
  "business administration and computer science double degree": [
    "bba/bcs",
    "bba and bcs",
    "bba/bmath or bba/cs",
  ],
};

/** Degree-type substring (inside the program name's parentheses) → faculty. */
const DEGREE_FACULTY: Array<[string, Faculty]> = [
  ["bachelor of applied science", "engineering"],
  ["bachelor of software engineering", "engineering"],
  ["bachelor of architectural studies", "engineering"],
  ["bachelor of mathematics", "mathematics"],
  ["bachelor of computer science", "mathematics"],
  ["bachelor of computing and financial management", "mathematics"],
  ["bachelor of environmental studies", "environment"],
  ["bachelor of arts", "arts"],
  ["bachelor of science", "science"],
  ["bachelor of public health", "health"],
];

/** Faculty from the degree-type clause inside the name, or null if ambiguous. */
function facultyFromName(name: string): Faculty | null {
  const lower = name.toLowerCase();
  for (const [needle, faculty] of DEGREE_FACULTY) {
    if (lower.includes(needle)) return faculty;
  }
  return null;
}

// A ProgramIdentity (+ optional spec name as an extra matchable name), or null
// for an unknown id. Index-level: matching needs names + faculty, not rules.
export function programIdentity(
  programId: string | null | undefined,
  specializationId?: string | null,
): ProgramIdentity | null {
  if (!programId) return null;
  const meta = INDEX[programId];
  if (!meta) return null;
  const short = shortName(meta.name).toLowerCase();
  const names = new Set<string>([
    short,
    ...(PROGRAM_RESTRICTION_ALIASES[short] ?? []),
  ]);
  if (specializationId) {
    const spec = meta.specializations?.find((s) => s.slug === specializationId);
    if (spec) names.add(spec.name.toLowerCase());
  }
  return {
    programId,
    names: [...names],
    faculty: facultyFromName(meta.name),
  };
}

// One identity per program on a plan (double degrees carry >1); unknown ids
// drop. Lets eligibility judge a restriction against all the student's programs.
export function programIdentities(
  programIds: readonly string[] | null | undefined,
  specializationIds: Record<string, string> = {},
): ProgramIdentity[] {
  return (programIds ?? [])
    .map((id) => programIdentity(id, specializationIds[id] ?? null))
    .filter((p): p is ProgramIdentity => p !== null);
}

// Lowercased set of every program short name + alias — the recognition
// vocabulary for restriction matching. Cached.
let shortNamesCache: ReadonlySet<string> | null = null;
export function programShortNames(): ReadonlySet<string> {
  if (shortNamesCache) return shortNamesCache;
  const out = new Set<string>();
  for (const meta of Object.values(INDEX)) {
    const short = shortName(meta.name).toLowerCase();
    out.add(short);
    for (const alias of PROGRAM_RESTRICTION_ALIASES[short] ?? [])
      out.add(alias);
  }
  shortNamesCache = out;
  return out;
}

// Longest span among the given programs (a double degree runs as long as its
// longer leg); 8 when none/unknown.
export function programIdsTermSpan(programIds: readonly string[]): number {
  let span = 0;
  for (const id of programIds) {
    const meta = INDEX[id];
    if (meta) span = Math.max(span, programTermSpan(meta));
  }
  return span || DEFAULT_TERM_SPAN;
}
